services:
  canvas-admin-rubric:
    build: .
    container_name: canvas_admin_rubric
    restart: unless-stopped

    ports:
      - "8501:8501"

    read_only: true

    tmpfs:
      - /tmp
      - /app/.streamlit

    security_opt:
      - no-new-privileges:true

    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G

    environment:
      - "TZ=${TZ}"
